# Cartella in cui sono memorizzate le librerie
LIBS = ./lib

# Compilatore e relative opzioni
CC = gcc -std=c99
CFLAGS = -g -Wall -Werror -pedantic -pthread -O3 -L $(LIBS) -I $(LIBS)

# Creatore di librerie e relative opzioni
AR = ar
ARFLAGS = rvs